name: deploy to Prod

on:
  push:
    branches: [prod]

jobs:
  worker:
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners
    runs-on: ubuntu-16.04
    steps:
      - name: Get code
        uses: actions/checkout@v2

      # https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install
        run: npm ci

      - name: Build
        run: npm run website:build:prod

      - name: Release
        if: success()
        run: npx semantic-release
        env:
          GITHUB_TOKEN: 3c773364199dda11acd405583682aa02f0a826d0

      - name: Configure AWS credentials
        if: success()
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAT6H6ASAMSAJB6JON
          aws-secret-access-key: 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
          aws-region: us-east-1

      - name: Remove files to the test website with the AWS CLI
        if: success()
        run: |
          aws s3 rm s3://monitor-website-prod --recursive

      - name: Copy files to the test website with the AWS CLI
        if: success()
        run: |
          aws s3 sync ./www s3://monitor-website-prod --acl public-read

      - name: Invalidation distribution with the AWS CLI
        if: success()
        run: |
          aws cloudfront create-invalidation --distribution-id E1A07ZOXRSGPT0 --paths '/*'
